MemoryCellInputFile: configs/tech_configs/sample_cells/sample_PCRAM_cell.yaml

ProcessNode: 130
DeviceRoadmap: HP

CacheAccessMode: Normal
Associativity: 8  # For cache only

OutputDirectory: 
OutputFilePrefix: sample_PCRAM_130nm_result
EnablePruning: Yes

LocalWire:
  Type: LocalAggressive
  RepeaterType: RepeatedNone
  UseLowSwing: No

GlobalWire:
  Type: GlobalAggressive
  RepeaterType: RepeatedNone
  UseLowSwing: No

Routing: H-tree

InternalSensing: true

Temperature: 370  # Kelvin
RetentionTime: 40  # microseconds

BufferDesignOptimization: latency
