system:
  DesignTarget: cache

  Capacity: 
    Value: 128
    Unit: KB
  
  WordWidth: 128 # bits
  
  OptimizationTarget: WriteEDP

apps:
  run: existing
  profiler: sniper
  multithread: false
  patternconfig_path: configs/sniper_run_config_existing/memsyspatternconfig_test_sniper.json


tech:
  run: existing
  array_characterization_result_path: configs/sniper_run_config_existing/sample_FeFET_32nm_result_128KB_WriteEDP.yaml